#!/usr/bin/env bash
# Configures the nginx server to listen to port 80 and kills the process eventually
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /run/nginx.pid)"
