#!/usr/bin/env bash
# fizzbuzz:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5

number=1
while ((number<=100)); do
    if ((number%15==0)); then
        echo "FizzBuzz"
    elif ((number%3==0)); then
        echo "Fizz"
    elif ((number%5==0)); then
        echo "Buzz"
    else
        echo "$number"
    fi
    ((number++))
done
